# Generated by Django 3.2.3 on 2021-07-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210704_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='float',
            old_name='Val_Max',
            new_name='FVal_Max',
        ),
        migrations.RenameField(
            model_name='float',
            old_name='Val_Min',
            new_name='FVal_Min',
        ),
        migrations.RenameField(
            model_name='int',
            old_name='Val_Max',
            new_name='IVal_Max',
        ),
        migrations.RenameField(
            model_name='int',
            old_name='Val_Min',
            new_name='IVal_Min',
        ),
    ]
