# Generated by Django 3.2.3 on 2021-07-22 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20210715_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='services',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='domaine',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='extension',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='nbcolonnes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='nblignes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='taille',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
