# Generated by Django 3.2.3 on 2021-07-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210723_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='poids',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
