# Generated by Django 3.2.3 on 2021-08-03 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_metadata_poids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, max_length=200, null=True)),
                ('date_min', models.DateField()),
                ('date_max', models.DateField()),
                ('MetaData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.metadata')),
            ],
        ),
    ]
