# Generated by Django 3.2.3 on 2021-08-03 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='semantic_rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=200)),
                ('attribut1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.metadata')),
            ],
        ),
    ]
