# Generated by Django 3.2.3 on 2021-08-03 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_semantic_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='semantic_rules',
            name='attribut2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribut2', to='app.metadata'),
        ),
        migrations.AlterField(
            model_name='semantic_rules',
            name='attribut1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribut1', to='app.metadata'),
        ),
    ]
