# Generated by Django 3.2.3 on 2021-10-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210803_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Entité_commerciale',
        ),
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='sous_categorie',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='application',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='user',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_suplémentaire',
        ),
        migrations.RemoveField(
            model_name='description',
            name='fonctionnalité',
        ),
        migrations.RemoveField(
            model_name='description',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='description_suplémentaire',
            name='langue',
        ),
        migrations.RemoveField(
            model_name='description_suplémentaire',
            name='modele_prix',
        ),
        migrations.RemoveField(
            model_name='description_suplémentaire',
            name='plateforme',
        ),
        migrations.RemoveField(
            model_name='description_suplémentaire',
            name='période_essaie',
        ),
        migrations.RemoveField(
            model_name='description_suplémentaire',
            name='type_business',
        ),
        migrations.RemoveField(
            model_name='formulaire_app',
            name='fonctionnalité',
        ),
        migrations.RemoveField(
            model_name='formulaire_app',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='formulaire_app',
            name='langue',
        ),
        migrations.RemoveField(
            model_name='formulaire_app',
            name='modele_prix',
        ),
        migrations.RemoveField(
            model_name='formulaire_app',
            name='plateforme',
        ),
        migrations.RemoveField(
            model_name='formulaire_app',
            name='type_business',
        ),
        migrations.RemoveField(
            model_name='formulaire_app',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sous_categorie',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='services',
            name='auteur',
        ),
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='float',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='int',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='semantic_rules',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='string',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Avis',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Description_suplémentaire',
        ),
        migrations.DeleteModel(
            name='Entité_commerciale',
        ),
        migrations.DeleteModel(
            name='Fonctionnalité',
        ),
        migrations.DeleteModel(
            name='formulaire_app',
        ),
        migrations.DeleteModel(
            name='Langue',
        ),
        migrations.DeleteModel(
            name='Modele_prix',
        ),
        migrations.DeleteModel(
            name='Plateforme',
        ),
        migrations.DeleteModel(
            name='Prix',
        ),
        migrations.DeleteModel(
            name='Période_essaie',
        ),
        migrations.DeleteModel(
            name='Sous_categorie',
        ),
        migrations.DeleteModel(
            name='Type_business',
        ),
    ]
